### ISSUE TITLE
America timezone selection seems to be defaulting to America/Anchorage 

### ISSUE THREAD

**Issue by joshschmelzle** [WLAN-Pi/wlanpi-fpms#116]
Setting the timezone to America/Phoenix sets the timezone to America/Anchorage which is incorrect due to Alaska Standard Time GMT-9 when it should be Mountain GMT-7.

Steps to reproduce:

On FPMS navigate to the following:

- System > Settings > Date & Time > Set Timezone > Manual > America > Phoenix

Looks like other settings also set to America/Anchorage incorrectly:

- System > Settings > Date & Time > Set Timezone > Manual > America > Denver

- System > Settings > Date & Time > Set Timezone > Manual > America > Los Angeles
 
- System > Settings > Date & Time > Set Timezone > Manual > America > New York
 
- System > Settings > Date & Time > Set Timezone > Manual > America > Chicago

![image](https://github.com/WLAN-Pi/wlanpi-fpms/assets/13954434/5d2eb992-da21-482a-8516-6ac16b195855)

![image](https://github.com/WLAN-Pi/wlanpi-fpms/assets/13954434/20b1ca36-521f-47b5-97e7-7a1d4466782c)

**Comment by adriangranados** [comment]
I broke it on my last refactoring to add the "Settings" menu but should be fixed now.

**Comment by joshschmelzle** [comment]
Thanks Adrian. I just tested and confirmed the fix is available in 1.3.4.
