### ISSUE TITLE
Switching modes doesn't work

### ISSUE THREAD

**Issue by adriangranados** [WLAN-Pi/wlanpi-fpms#12]
All modes give "X is not available." Wrong path for the switcher script? Or is the switcher script missing?

**Comment by jiribrejcha** [comment]
No modes have been added to the Pro yet.

Each mode will be packaged and installed as its own Debian package. We plan to make FPMS extensible, so that these new modes could add their new menu items to FPMS: https://github.com/WLAN-Pi/wlanpi-fpms/issues/1
