### ISSUE TITLE
[BUG]: FPMS no longer working after update/upgrade of WLANPI Pro

### ISSUE THREAD

**Issue by jmack778** [WLAN-Pi/wlanpi-fpms#128]
### What happened?

Today I performed the following commands on my WLANPi to update and upgrade to the latest firmware and now the FPMS no longer works.  I've used commands provided to me on Case #76 however no change, also rebooted it and still no FPMS.  Any ideas how to fix this?

Commands Performed:
sudo dpkg --configure -a
sudo apt update
sudo apt upgrade

### Relevant log output

```shell
wlanpi@mackeypi-53:~ $ sudo dpkg --configure -a
[sudo] password for wlanpi: 
wlanpi@mackeypi-53:~ $ sudo apt update
Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
Hit:2 http://deb.debian.org/debian bullseye InRelease                                                                               
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease                                                                       
Hit:4 http://deb.debian.org/debian bullseye-backports InRelease                                                                     
Hit:5 https://apt.grafana.com stable InRelease                                                                                      
Hit:6 https://repos.influxdata.com/debian bullseye InRelease                                                                        
Get:7 https://pkgs.tailscale.com/stable/debian bullseye InRelease                                                                   
Hit:8 https://www.kismetwireless.net/repos/apt/release/bullseye bullseye InRelease                                                  
Hit:9 http://archive.raspberrypi.org/debian bullseye InRelease                                                        
Hit:10 https://packagecloud.io/wlanpi/main/debian bullseye InRelease                            
Fetched 6,581 B in 2s (2,811 B/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
wlanpi@mackeypi-53:~ $ sudo apt upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following package was automatically installed and is no longer required:
  raspinfo
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
wlanpi@mackeypi-53:~ $ sudo reboot
```

### How often does this bug happen?

Every time

### What version are you using?

VERSION="11 (bullseye)"

### Self Service

- [ ] I would be willing to fix this bug myself.

### Guidelines and Policies

- [X] I have read the contributing guidelines and agree to follow the code of conduct and contribution policies.

**Comment by jmack778** [comment]
wlanpi@mackeypi-53:~ $ systemctl status wlanpi-fpms
● wlanpi-fpms.service - Front Panel Menu System for the WLAN Pi OLED display
     Loaded: loaded (/lib/systemd/system/wlanpi-fpms.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2024-12-12 08:48:09 CST; 10min ago
    Process: 624 ExecStart=/usr/sbin/fpms (code=exited, status=1/FAILURE)
   Main PID: 624 (code=exited, status=1/FAILURE)
        CPU: 445ms

Dec 12 08:48:08 mackeypi-53 fpms[624]:     from fpms.__main__ import main
Dec 12 08:48:08 mackeypi-53 fpms[624]:   File "/opt/wlanpi-fpms/lib/python3.9/site-packages/fpms/__main__.py", line 2, in <module>
Dec 12 08:48:08 mackeypi-53 fpms[624]:     from fpms import fpms
Dec 12 08:48:08 mackeypi-53 fpms[624]:   File "/opt/wlanpi-fpms/lib/python3.9/site-packages/fpms/fpms.py", line 13, in <module>
Dec 12 08:48:08 mackeypi-53 fpms[624]:     from gi.repository import GLib
Dec 12 08:48:08 mackeypi-53 fpms[624]:   File "/opt/wlanpi-fpms/lib/python3.9/site-packages/gi/importer.py", line 133, in create_mod>
Dec 12 08:48:08 mackeypi-53 fpms[624]:     raise ImportError('cannot import name %s, '
Dec 12 08:48:08 mackeypi-53 fpms[624]: ImportError: cannot import name GLib, introspection typelib not found
Dec 12 08:48:09 mackeypi-53 systemd[1]: wlanpi-fpms.service: Main process exited, code=exited, status=1/FAILURE
Dec 12 08:48:09 mackeypi-53 systemd[1]: wlanpi-fpms.service: Failed with result 'exit-code'.
lines 1-17/17 (END)

**Comment by jmack778** [comment]
Dec 12 08:19:55 mackeypi-53 sudo[17192]: pam_unix(sudo:session): session closed for user root
Dec 12 08:21:09 mackeypi-53 sudo[20313]:     root : PWD=/opt/wlanpi-fpms/lib/python3.9/site-packages/fpms ; USER=root ; COMMAND=/opt>
Dec 12 08:21:09 mackeypi-53 sudo[20313]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=0)
Dec 12 08:21:09 mackeypi-53 sudo[20313]: pam_unix(sudo:session): session closed for user root
Dec 12 08:22:22 mackeypi-53 sudo[23432]:     root : PWD=/opt/wlanpi-fpms/lib/python3.9/site-packages/fpms ; USER=root ; COMMAND=/opt>
Dec 12 08:22:22 mackeypi-53 sudo[23432]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=0)
Dec 12 08:22:22 mackeypi-53 sudo[23432]: pam_unix(sudo:session): session closed for user root
Dec 12 08:23:36 mackeypi-53 sudo[26851]:     root : PWD=/opt/wlanpi-fpms/lib/python3.9/site-packages/fpms ; USER=root ; COMMAND=/opt>
Dec 12 08:23:36 mackeypi-53 sudo[26851]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=0)
Dec 12 08:23:36 mackeypi-53 sudo[26851]: pam_unix(sudo:session): session closed for user root
Dec 12 08:24:49 mackeypi-53 sudo[30528]:     root : PWD=/opt/wlanpi-fpms/lib/python3.9/site-packages/fpms ; USER=root ; COMMAND=/opt>
Dec 12 08:24:49 mackeypi-53 sudo[30528]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=0)
Dec 12 08:24:49 mackeypi-53 sudo[30528]: pam_unix(sudo:session): session closed for user root
Dec 12 08:38:36 mackeypi-53 systemd[1]: Stopping Front Panel Menu System for the WLAN Pi OLED display...
Dec 12 08:38:36 mackeypi-53 systemd[1]: wlanpi-fpms.service: Succeeded.
Dec 12 08:38:36 mackeypi-53 systemd[1]: Stopped Front Panel Menu System for the WLAN Pi OLED display.
Dec 12 08:38:36 mackeypi-53 systemd[1]: wlanpi-fpms.service: Consumed 2min 19.425s CPU time.
Dec 12 08:38:36 mackeypi-53 systemd[1]: Started Front Panel Menu System for the WLAN Pi OLED display.
Dec 12 08:38:37 mackeypi-53 fpms[44361]: Traceback (most recent call last):
Dec 12 08:38:37 mackeypi-53 fpms[44361]:   File "/usr/sbin/fpms", line 5, in <module>
Dec 12 08:38:37 mackeypi-53 fpms[44361]:     from fpms.__main__ import main
Dec 12 08:38:37 mackeypi-53 fpms[44361]:   File "/opt/wlanpi-fpms/lib/python3.9/site-packages/fpms/__main__.py", line 2, in <module>
Dec 12 08:38:37 mackeypi-53 fpms[44361]:     from fpms import fpms
Dec 12 08:38:37 mackeypi-53 fpms[44361]:   File "/opt/wlanpi-fpms/lib/python3.9/site-packages/fpms/fpms.py", line 13, in <module>
Dec 12 08:38:37 mackeypi-53 fpms[44361]:     from gi.repository import GLib
Dec 12 08:38:37 mackeypi-53 fpms[44361]:   File "/opt/wlanpi-fpms/lib/python3.9/site-packages/gi/importer.py", line 133, in create_m>
Dec 12 08:38:37 mackeypi-53 fpms[44361]:     raise ImportError('cannot import name %s, '
Dec 12 08:38:37 mackeypi-53 fpms[44361]: ImportError: cannot import name GLib, introspection typelib not found
Dec 12 08:38:37 mackeypi-53 systemd[1]: wlanpi-fpms.service: Main process exited, code=exited, status=1/FAILURE
Dec 12 08:38:37 mackeypi-53 systemd[1]: wlanpi-fpms.service: Failed with result 'exit-code'.
-- Boot e9fa0309292e4195a78334f571040ddd --
Dec 12 08:41:44 mackeypi-53 systemd[1]: Started Front Panel Menu System for the WLAN Pi OLED display.
Dec 12 08:41:47 mackeypi-53 fpms[673]: Traceback (most recent call last):
Dec 12 08:41:47 mackeypi-53 fpms[673]:   File "/usr/sbin/fpms", line 5, in <module>
Dec 12 08:41:47 mackeypi-53 fpms[673]:     from fpms.__main__ import main
Dec 12 08:41:47 mackeypi-53 fpms[673]:   File "/opt/wlanpi-fpms/lib/python3.9/site-packages/fpms/__main__.py", line 2, in <module>
Dec 12 08:41:47 mackeypi-53 fpms[673]:     from fpms import fpms
Dec 12 08:41:47 mackeypi-53 fpms[673]:   File "/opt/wlanpi-fpms/lib/python3.9/site-packages/fpms/fpms.py", line 13, in <module>
Dec 12 08:41:47 mackeypi-53 fpms[673]:     from gi.repository import GLib
Dec 12 08:41:47 mackeypi-53 fpms[673]:   File "/opt/wlanpi-fpms/lib/python3.9/site-packages/gi/importer.py", line 133, in create_mod>
Dec 12 08:41:47 mackeypi-53 fpms[673]:     raise ImportError('cannot import name %s, '
Dec 12 08:41:47 mackeypi-53 fpms[673]: ImportError: cannot import name GLib, introspection typelib not found
Dec 12 08:41:47 mackeypi-53 systemd[1]: wlanpi-fpms.service: Main process exited, code=exited, status=1/FAILURE
Dec 12 08:41:47 mackeypi-53 systemd[1]: wlanpi-fpms.service: Failed with result 'exit-code'.
-- Boot 823f020be04148ba9485e8102cc6b07a --
Dec 12 08:42:20 mackeypi-53 systemd[1]: Started Front Panel Menu System for the WLAN Pi OLED display.
Dec 12 08:42:23 mackeypi-53 fpms[615]: Traceback (most recent call last):
Dec 12 08:42:23 mackeypi-53 fpms[615]:   File "/usr/sbin/fpms", line 5, in <module>
Dec 12 08:42:23 mackeypi-53 fpms[615]:     from fpms.__main__ import main
Dec 12 08:42:23 mackeypi-53 fpms[615]:   File "/opt/wlanpi-fpms/lib/python3.9/site-packages/fpms/__main__.py", line 2, in <module>
Dec 12 08:42:23 mackeypi-53 fpms[615]:     from fpms import fpms
Dec 12 08:42:23 mackeypi-53 fpms[615]:   File "/opt/wlanpi-fpms/lib/python3.9/site-packages/fpms/fpms.py", line 13, in <module>
Dec 12 08:42:23 mackeypi-53 fpms[615]:     from gi.repository import GLib
Dec 12 08:42:23 mackeypi-53 fpms[615]:   File "/opt/wlanpi-fpms/lib/python3.9/site-packages/gi/importer.py", line 133, in create_mod>
Dec 12 08:42:23 mackeypi-53 fpms[615]:     raise ImportError('cannot import name %s, '
Dec 12 08:42:23 mackeypi-53 fpms[615]: ImportError: cannot import name GLib, introspection typelib not found
Dec 12 08:42:23 mackeypi-53 systemd[1]: wlanpi-fpms.service: Main process exited, code=exited, status=1/FAILURE
Dec 12 08:42:23 mackeypi-53 systemd[1]: wlanpi-fpms.service: Failed with result 'exit-code'.
-- Boot e296c0cac9a14876ab924165f1f7edd2 --
Dec 12 08:48:05 mackeypi-53 systemd[1]: Started Front Panel Menu System for the WLAN Pi OLED display.
Dec 12 08:48:08 mackeypi-53 fpms[624]: Traceback (most recent call last):
Dec 12 08:48:08 mackeypi-53 fpms[624]:   File "/usr/sbin/fpms", line 5, in <module>
Dec 12 08:48:08 mackeypi-53 fpms[624]:     from fpms.__main__ import main
Dec 12 08:48:08 mackeypi-53 fpms[624]:   File "/opt/wlanpi-fpms/lib/python3.9/site-packages/fpms/__main__.py", line 2, in <module>
Dec 12 08:48:08 mackeypi-53 fpms[624]:     from fpms import fpms
Dec 12 08:48:08 mackeypi-53 fpms[624]:   File "/opt/wlanpi-fpms/lib/python3.9/site-packages/fpms/fpms.py", line 13, in <module>
Dec 12 08:48:08 mackeypi-53 fpms[624]:     from gi.repository import GLib
Dec 12 08:48:08 mackeypi-53 fpms[624]:   File "/opt/wlanpi-fpms/lib/python3.9/site-packages/gi/importer.py", line 133, in create_mod>
Dec 12 08:48:08 mackeypi-53 fpms[624]:     raise ImportError('cannot import name %s, '
Dec 12 08:48:08 mackeypi-53 fpms[624]: ImportError: cannot import name GLib, introspection typelib not found
Dec 12 08:48:09 mackeypi-53 systemd[1]: wlanpi-fpms.service: Main process exited, code=exited, status=1/FAILURE
Dec 12 08:48:09 mackeypi-53 systemd[1]: wlanpi-fpms.service: Failed with result 'exit-code'.
lines 4135-4191/4191 (END)

**Comment by adriangranados** [comment]
I don't know what could have caused the error, but it seems some packages may have been corrupted.

At this point, reflashing the SD card using the latest WLAN Pi image is the easiest solution (keep in mind any customizations you might have made to the image will be lost as you will be starting from scratch).

The latest image can be found here: https://github.com/WLAN-Pi/pi-gen/releases/tag/v3.2.3

**Comment by jmack778** [comment]
Thank you for the reply and image location, I've never flashed this onto the SD card before.  Do you have instructions as to how to accomplish this for my WLANPi?

**Comment by adriangranados** [comment]
See https://www.wlanpi.com/flash-sd-card for instructions. After reflashing, log in using SSH and set a new password (the default username/password is wlanpi). That should be it.

**Comment by jmack778** [comment]
This worked, thank you for the information.
