### ISSUE TITLE
Package FPMS and install to its own wlanpi-fpms Python virtual environment

### ISSUE THREAD

**Issue by jiribrejcha** [WLAN-Pi/wlanpi-fpms#4]
Create a Debian package with the latest FPMS code. The deb package should install FPMS to its own `wlanpi-fpms` Python virtual environment.

https://dh-virtualenv.readthedocs.io/en/1.2.1/
https://pi3g.com/2019/04/19/packaging-python-projects-for-debian-raspbian-with-dh-virtualenv/

**Comment by wifinigel** [comment]
Branch: https://github.com/WLAN-Pi/wlanpi-fpms/tree/venv

**Comment by jiribrejcha** [comment]
Josh did this. We now have wlanpi-fpms 1.0.5 available from packagecloud/main.

**Comment by joshschmelzle** [comment]
Done in 3c168873734d06995a283591e0749cb7411cda1c
