### ISSUE TITLE
Display issue with IP on Cloud Tests

### ISSUE THREAD

**Issue by joshschmelzle** [WLAN-Pi/wlanpi-fpms#42]
Example 1: 

<img width="160" alt="image" src="https://user-images.githubusercontent.com/13954434/149016154-a8426b6a-a22b-4c85-ae6e-56b8433b758a.png">

Example 2:

<img width="154" alt="image" src="https://user-images.githubusercontent.com/13954434/149016186-2a5cbe08-8b96-4aa9-9001-9fa4659f92c8.png">

**Comment by adriangranados** [comment]
I was unable to reproduce this issue... my guess is that this was caused by manually running FPMS (from dev venv) while the FPMS service was still active.

**Comment by adriangranados** [comment]
The issue does exist in the latest version of FPMS. I will investigate.

**Comment by joshschmelzle** [comment]
Closing as haven't been able to reproduce.
