### ISSUE TITLE
Reachability indicator doesn't work when tethered to an Android/iOS device

### ISSUE THREAD

**Issue by adriangranados** [WLAN-Pi/wlanpi-fpms#53]
The internet reachability status icon, currently does not show the WLAN Pi has internet connectivity even though it does when tethered to an Android/iOS device for internet

**Comment by adriangranados** [comment]
Here's how to do tethering so I can reproduce it: https://www.jiribrejcha.net/2020/02/iphone-usb-tethering-on-wlan-pi/

**Comment by jolla** [comment]
iOS devices uses eth1 as the interface, android devices use usb1
