### ISSUE TITLE
Sometimes the QR code is not displayed right after starting the Profiler

### ISSUE THREAD

**Issue by adriangranados** [WLAN-Pi/wlanpi-fpms#54]
This is happening because the profiler is taking longer than expected to create the file that contains the SSID. We need to wait longer.

**Comment by adriangranados** [comment]
Josh found and fixed the underlying cause delaying profiler startup.

**Comment by joshschmelzle** [comment]
Thanks Adrian for closing the issue. Just in case someone stumbles on this, on first run after initial boot, profiler runs `wpa_cli -i <iface> terminate`, and it was taking up to 10 seconds to terminate wpa_supplicant on wlan0.
