### ISSUE TITLE
Please Add Required FPMS Images to the images/128x64 directory

### ISSUE THREAD

**Issue by iamk3** [WLAN-Pi/wlanpi-fpms#64]
The images/128x64 folder is missing reboot, shutdown, and wlanpi0-4 images and causes a failure for fpms to start.

**Comment by joshschmelzle** [comment]
What does your hardware setup look like? Which OLED are you using?

**Comment by iamk3** [comment]
I am currently working on two options. 

1. RPi 3b+ with a PoE hat and I2C 128x64 OLED which I was just able to get working yesterday.
2. RPi 4b+ 8GB in a Pi-Top DIY case. (this is the way I'd ultimately like to go as it makes a nice self-contained unit)

Of course this is until the Pro is widely available! :)

**Comment by joshschmelzle** [comment]
Unfortunately we're not currently planning to take on supporting both 128x128 and 128x64 resolutions from the same version of FPMS.

We're currently using a 128x128 SPI display on the Pro units. We are working on putting some kit recommendations together which include a 128x128 SPI display. There is one from Waveshare which should work.

**Comment by iamk3** [comment]
Yeah, I understand. I was really hoping to get the pi-top option going in the mean time because it is completely contained. Can you share a link to the particular 128x128 display? Looking through the code, I was thinking it was [this one](https://www.amazon.com/waveshare-1-44inch-Interface-Direct-pluggable-Raspberry/dp/B077Z7DWW1/ref=sr_1_5?crid=22G103X0Q1OQY&keywords=waveshare+spi+128x128&qid=1647462515&sprefix=waveshare+spi+128x128%2Caps%2C71&sr=8-5), but unfortunately that would take up the pins that I am using for PoE. 

I considered giving [this one](https://www.amazon.com/1-5inch-RGB-OLED-Module-Communicating/dp/B07DB5YFGW/ref=sr_1_4?crid=22G103X0Q1OQY&keywords=waveshare+spi+128x128&qid=1647462515&sprefix=waveshare+spi+128x128%2Caps%2C71&sr=8-4) a try, but it is more expensive.

If you have a list going for a community edition, I'd be happy to do some beta testing for y'all! Hopefully be helpful and then I'm not flying solo here either! haha...

**Comment by joshschmelzle** [comment]
The 1.44 inch one will work when touching a file at `/boot/waveshare` on the uSD. The second one (1.5 inch) can also be made to work, but has no buttons 👎🏻 . There are for sure a few tradeoffs depending on which one is selected for the DIY kit.

**Comment by joshschmelzle** [comment]
Jiri put this together for us. @iamk3 check it out. https://userguide.wlanpi.com/v/wlan-pi-community-edition/guides/supported-hardware

**Comment by iamk3** [comment]
> Jiri put this together for us. @iamk3 check it out. https://userguide.wlanpi.com/v/wlan-pi-community-edition/guides/supported-hardware

Thank you very much for your assistance!
