### ISSUE TITLE
Updating packages from FPMS may break FPMS

### ISSUE THREAD

**Issue by adriangranados** [WLAN-Pi/wlanpi-fpms#76]
If one of the packages being updated is wlanpi-fpms, then updating from FPMS causes the update process to be interrupted when the FPMS service is restarted, breaking the package installation. Running `sudo dpkg --configure -a` from a terminal should resolve the issue.

**Comment by jmack778** [comment]
I ran this command provided and restarted FPMS and it still fails, any ideas how to correct this?

**Comment by jmack778** [comment]
Here is the log status:

Jan 24 16:23:35 mackeypi-53 fpms[6894]:   File "/opt/wlanpi-fpms/lib/python3.9/site-packages/gpiozero/pins/__init__.py", line 432, in <lambda>
Jan 24 16:23:35 mackeypi-53 fpms[6894]:     lambda self, value: self._set_when_changed(value),
Jan 24 16:23:35 mackeypi-53 fpms[6894]:   File "/opt/wlanpi-fpms/lib/python3.9/site-packages/gpiozero/pins/pi.py", line 319, in _set_when_changed
Jan 24 16:23:35 mackeypi-53 fpms[6894]:     self._enable_event_detect()
Jan 24 16:23:35 mackeypi-53 fpms[6894]:   File "/opt/wlanpi-fpms/lib/python3.9/site-packages/gpiozero/pins/rpigpio.py", line 226, in _enable_event_detect
Jan 24 16:23:35 mackeypi-53 fpms[6894]:     GPIO.add_event_detect(
Jan 24 16:23:35 mackeypi-53 fpms[6894]: RuntimeError: Failed to add edge detection
Jan 24 16:23:35 mackeypi-53 systemd[1]: wlanpi-fpms.service: Main process exited, code=exited, status=1/FAILURE
Jan 24 16:23:35 mackeypi-53 systemd[1]: wlanpi-fpms.service: Failed with result 'exit-code'.
Jan 24 16:23:35 mackeypi-53 systemd[1]: wlanpi-fpms.service: Consumed 1.042s CPU time.

**Comment by adriangranados** [comment]
What's the output of `uname -a`?

**Comment by jmack778** [comment]
Linux mackeypi-53 6.7.1-v8-wlanpi+ #1 SMP PREEMPT Mon Jan 22 17:15:38 UTC 2024 aarch64 GNU/Linux

**Comment by adriangranados** [comment]
It appears you caught us in the middle of some updates to our packages repo. Please run the following commands to update FPMS (and other wlanpi-related packages that should be updated, too):
```
sudo apt update
sudo apt upgrade
```
 That should fix it. Otherwise, let us know.

**Comment by jmack778** [comment]
It worked, thanks for your help on this.  I look forward to your deep dive "Mastering WiFi Explorer Pro" next month at the WLPC in Phoenix.  Take care.

**Comment by adriangranados** [comment]
Fixed in d57a1ec592f782b3fe3e8c865040e61069e06250.

**Comment by adriangranados** [comment]
We've removed the ability to run software updates from FPMS, so this has become a non-issue.

**Comment by adriangranados** [comment]
We've removed the ability to run software updates from FPMS, so this has become a non-issue.
